@echo off
rem ===========================================================================
rem  Jarvis - uninstall.
rem
rem  Removes ONLY these three things, and nothing else:
rem    1. the local virtual environment  .venv\        (created by setup.cmd)
rem    2. the per-user data folder       %LOCALAPPDATA%\Jarvis
rem    3. the stored API key             Windows Credential Manager target
rem                                      Jarvis/openai_api_key
rem
rem  It does NOT touch your Python installation, does NOT delete the source
rem  folder, does NOT need administrator rights, and does NOT ask for UAC.
rem
rem  Usage:
rem      uninstall.cmd /dryrun   list what WOULD be removed, delete nothing
rem      uninstall.cmd           asks for confirmation, then removes the above
rem
rem  Nothing is ever deleted without you typing YES at the prompt.
rem ===========================================================================
setlocal EnableExtensions
cd /d "%~dp0"

set "ROOT=%~dp0"
set "VENV=%ROOT%.venv"
set "DATA=%LOCALAPPDATA%\Jarvis"
set "CRED=Jarvis/openai_api_key"

set "DRYRUN=0"
if /i "%~1"=="/dryrun" set "DRYRUN=1"
if /i "%~1"=="--dry-run" set "DRYRUN=1"
if /i "%~1"=="/n"  set "DRYRUN=1"

set "ACT=WILL REMOVE"
if "%DRYRUN%"=="1" set "ACT=WOULD REMOVE"

echo ===========================================================================
echo  Jarvis uninstall
if "%DRYRUN%"=="1" echo  MODE: DRY RUN - nothing will be deleted.
if "%DRYRUN%"=="0" echo  MODE: INTERACTIVE - you will be asked to confirm.
echo ===========================================================================
echo.
echo %ACT%  "%VENV%"
echo     the local virtual environment created by setup.cmd. It is ~250 MB and
echo     is regenerated by setup.cmd whenever you want it back.
echo.
echo %ACT%  "%DATA%"
echo     your per-user data:
echo       config.json    settings (engine choice, hotkeys, budgets, vocabulary)
echo       jarvis.db SQLite: dictation history, vocabulary, spend meter, tasks
echo       logs\          rotating logs (secrets are redacted before they are written)
echo       models\        downloaded wake-word model files
echo       audio\         scratch audio for the current utterance only
echo       secret.dpapi   DPAPI fallback key file, ONLY if Credential Manager failed
echo.
echo %ACT%  Windows Credential Manager target: %CRED%
echo     remove it with exactly:
echo         cmdkey /delete:Jarvis/openai_api_key
echo     (or open Control Panel ^> Credential Manager ^> Windows Credentials)
echo.
echo NOT removed: this source folder, your Python install, your dictation files
echo that you saved elsewhere, and any Start-menu shortcut you created by hand.
echo If you enabled "start at login" you may also want to delete:
echo     "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\Jarvis.lnk"
echo.

if "%DRYRUN%"=="1" goto :dryrun_end

echo Nothing has been deleted yet.
set /p "CONFIRM=Type YES (capitals) to delete the two folders and the API key, anything else to abort: "
if not "%CONFIRM%"=="YES" goto :aborted

echo.
if exist "%VENV%" (
  echo removing "%VENV%"
  rmdir /s /q "%VENV%"
)
if exist "%DATA%" (
  echo removing "%DATA%"
  rmdir /s /q "%DATA%"
)
echo removing the stored API key
cmdkey /delete:Jarvis/openai_api_key >nul 2>nul

echo.
echo ===========================================================================
echo  Done. The two folders and the credential entry are gone.
echo  Your Python installation and this source folder were left untouched.
echo ===========================================================================
exit /b 0

:dryrun_end
echo ===========================================================================
echo  DRY RUN complete - nothing was deleted.
echo  Re-run "uninstall.cmd" with no arguments to actually remove the above.
echo ===========================================================================
exit /b 0

:aborted
echo.
echo Aborted - nothing was deleted.
exit /b 0
